include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
linter:
  rules:
    unawaited_futures: true
    prefer_interpolation_to_compose_strings: false
    no_default_cases: true
    non_constant_identifier_names: false
    constant_identifier_names: false
