name: flutter_bitcoin
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH, Partial P2SH integration.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bip39: ^1.0.6
  bip32: ^2.0.0
  pointycastle: ^3.4.0
  hex: ^0.2.0
  bs58check: ^1.0.2
  meta: ^1.7.0
  bech32: ^0.2.1
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.19.3
